module.exports.CODE_OFFSET = 0;

module.exports.IDENTIFIER_OFFSET = 1;

module.exports.LENGTH_OFFSET_HIGH = 2;

module.exports.LENGTH_OFFSET_LOW = 3

const AUTHENTICATOR_OFFSET = 4;
module.exports.AUTHENTICATOR_OFFSET = AUTHENTICATOR_OFFSET;

const AUTHENTICATOR_LENGTH = 16;
module.exports.AUTHENTICATOR_LENGTH = AUTHENTICATOR_LENGTH;

module.exports.ATTRIBUTES_OFFSET = AUTHENTICATOR_OFFSET + AUTHENTICATOR_LENGTH;

module.exports.LENGTH_LENGTH = 2;